apiVersion: apps/v1
kind: Deployment
metadata:
  name: libp2p-nodes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: libp2p-nodes
  template:
    metadata:
      labels:
        app: libp2p-nodes
    spec:
      containers:
        - name: libp2p-node
          image: libp2p-node
          env:
            - name: DB_DSN
              value: "host=localhost user=postgres password=password dbname=libp2p sslmode=disable"
            - name: LISTEN_PORT
              value: "4001"
            - name: API_PORT
              value: "8080"
          ports:
            - containerPort: 8080
            - containerPort: 4001
